### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by calfino** [saburhb/FlyNetSim#4]
I run through several problems:

1. When I try to run FlyNetSim, the Network Simulator does not open, so I try to run it manually through console (./waf)

2. When I try to run the Network Simulator manually, it says that undefined reference to zmq_sendmsg().

3. When I try to run with gcc command it says undefined reference to main in function _start. 

4. Then I try to comment out the zmq_sendmsg() and try to run with waf command, and it says the same thing which is undefined reference to main in function _start.

Can somebody explain to me why is this happening and can help me to fix this problem?

All photos of screenshots will be attached, thank you!
![undefined-reference-to-symbol-zmq_sendmsg](https://user-images.githubusercontent.com/41240389/80590544-451b9200-8a46-11ea-8a0d-843642eae153.jpg)
![FlyNetSim-dont-open-NetworkSimulator](https://user-images.githubusercontent.com/41240389/80590549-46e55580-8a46-11ea-922c-7b54413d2aa0.jpg)
![_Start-undefined-reference-main](https://user-images.githubusercontent.com/41240389/80590551-48af1900-8a46-11ea-9b8d-907f90392a75.jpg)

**Comment by saburhb** [comment]
@calfino Did you complete the step to run "net_init.sh" . This script runs some patches including one that adds the linking in the wscript file. If your "net_init.sh" completes without error, you should not see any linking error.

**Comment by calfino** [comment]
I have retried the cloning and try it again but it still stuck at zmq_sendmsg, the installation is running well, but when i tried to run ./fly_init.sh it runs through several warnings.

./net_init.sh run succesfully
![Screenshot from 2020-05-06 22-56-31](https://user-images.githubusercontent.com/41240389/81199589-0b6dfc80-8fed-11ea-8fef-11982ca16d60.png)
./fly_init.sh warnings
![Screenshot from 2020-05-06 22-58-47](https://user-images.githubusercontent.com/41240389/81199706-3a846e00-8fed-11ea-8164-75aa0a3a4248.png)

**Comment by calfino** [comment]
@saburhb can u please help? thank you!

**Comment by saburhb** [comment]
If net_init.sh executed correctly, you should not get linking error for zmq_sendmsg. You can check 2 things if the zmq installation and linking done correctly. 
1) In the ns-3.27/wscript file, check if you have -lzmq and -lczmq
2) In /usr/lib/ folder , run : 
 ls -lrt */lib\*zmq.so 
You should get 2 files:  libzmq.so and libczmq.so

If both (1) and (2) checks are fine for you, you should not get the zmq linking error.

**Comment by calfino** [comment]
@saburhb I have checked those and they are all there, why am i still getting this error?
![Screenshot from 2020-05-09 02-15-21](https://user-images.githubusercontent.com/41240389/81440896-fb941b00-919a-11ea-8519-86a159d4dc99.png)

![Screenshot from 2020-05-09 02-08-15](https://user-images.githubusercontent.com/41240389/81440314-08fcd580-919a-11ea-8357-700b1f4f0c15.png)

**Comment by saburhb** [comment]
@calfino If you have all the linking elements in compilations, you should not get this error unless library path may be corrupted because of some other reasons. Note that, this software is being used by many people already and there has been no linking problem.  

At this moment I can only suggest you to try in another computer from scratch or on a fresh ubuntu 16.

**Comment by calfino** [comment]
@saburhb okay thanks for the help, really appreciate it!
